services:
  - type: web
    name: snake-social
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-social-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: snake-social-db
    plan: free
